// Shared by React.lazy and intent-based navigation preloading.
export const routeLoaders = {
  Inicio: () => import("@/pages/Inicio"),
  PersonasList: () => import("@/pages/PersonasList"),
  Apellidos: () => import("@/pages/Apellidos"),
  PersonaDetail: () => import("@/pages/PersonaDetail"),
  GenealogyProfilePage: () => import("@/pages/GenealogyProfilePage"),
  NuevaPersona: () => import("@/pages/NuevaPersona"),
  Arbol: () => import("@/pages/Arbol"),
  ArbolModerno: () => import("@/pages/ArbolModerno"),
  Familias: () => import("@/pages/Familias"),
  Documentos: () => import("@/pages/Documentos"),
  Fotos: () => import("@/pages/Fotos"),
  Buscar: () => import("@/pages/Buscar"),
  Investigacion: () => import("@/pages/Investigacion"),
  InvestigacionExterna: () => import("@/pages/InvestigacionExterna"),
  PersonasImportadasPendientes: () => import("@/pages/PersonasImportadasPendientes"),
  Importar: () => import("@/pages/Importar"),
  Agente: () => import("@/pages/Agente"),
  Asistente: () => import("@/pages/Asistente"),
  Credenciales: () => import("@/pages/Credenciales"),
  Parecidos: () => import("@/pages/Parecidos"),
  ADN: () => import("@/pages/ADN"),
  CuadrosIA: () => import("@/pages/CuadrosIA"),
  Coincidencias: () => import("@/pages/Coincidencias"),
  Pistas: () => import("@/pages/Pistas"),
  Hipotesis: () => import("@/pages/Hipotesis"),
  Inferencias: () => import("@/pages/Inferencias"),
  Lugares: () => import("@/pages/Lugares"),
  LineaDeTiempo: () => import("@/pages/LineaDeTiempo"),
  Configuracion: () => import("@/pages/Configuracion"),
  ConfigurarApp: () => import("@/pages/ConfigurarApp"),
  Fuentes: () => import("@/pages/Fuentes"),
  FamilySearchCallback: () => import("@/pages/FamilySearchCallback"),
  Fusionar: () => import("@/pages/Fusionar"),
  Sugerencias: () => import("@/pages/Sugerencias"),
  TareasIA: () => import("@/pages/TareasIA"),
  PersonaPublica: () => import("@/pages/PersonaPublica"),
  PersonaSlugRedirect: () => import("@/pages/PersonaSlugRedirect"),
  Calendario: () => import("@/pages/Calendario"),
  OAuthConsent: () => import("@/pages/OAuthConsent"),
  NotFound: () => import("@/pages/NotFound"),
};

const routes: Record<string, () => Promise<unknown>> = {
  "/oauth/consent": routeLoaders.OAuthConsent,
  "/inicio": routeLoaders.Inicio,
  "/arbol": routeLoaders.Arbol,
  "/arbol-moderno": routeLoaders.ArbolModerno,
  "/personas": routeLoaders.PersonasList,
  "/apellidos": routeLoaders.Apellidos,
  "/personas/nueva": routeLoaders.NuevaPersona,
  "/familias": routeLoaders.Familias,
  "/documentos": routeLoaders.Documentos,
  "/fotos": routeLoaders.Fotos,
  "/fuentes": routeLoaders.Fuentes,
  "/investigacion": routeLoaders.Investigacion,
  "/importadas-pendientes": routeLoaders.PersonasImportadasPendientes,
  "/investigacion-externa": routeLoaders.InvestigacionExterna,
  "/buscar": routeLoaders.Buscar,
  "/coincidencias": routeLoaders.Coincidencias,
  "/adn": routeLoaders.ADN,
  "/cuadros-ia": routeLoaders.CuadrosIA,
  "/importar": routeLoaders.Importar,
  "/agente": routeLoaders.Agente,
  "/asistente": routeLoaders.Asistente,
  "/credenciales": routeLoaders.Credenciales,
  "/parecidos": routeLoaders.Parecidos,
  "/pistas": routeLoaders.Pistas,
  "/hipotesis": routeLoaders.Hipotesis,
  "/inferencias": routeLoaders.Inferencias,
  "/fusionar": routeLoaders.Fusionar,
  "/sugerencias": routeLoaders.Sugerencias,
  "/tareas-ia": routeLoaders.TareasIA,
  "/lugares": routeLoaders.Lugares,
  "/linea-de-tiempo": routeLoaders.LineaDeTiempo,
  "/calendario": routeLoaders.Calendario,
  "/configuracion": routeLoaders.Configuracion,
  "/configurar-app": routeLoaders.ConfigurarApp,
};

export const routeLoaderFor = (path: string) => routes[path.split(/[?#]/)[0].replace(/\/$/, "") || "/inicio"];
