// Generated by scripts/sync-product.mjs. Do not edit.
import Foundation

enum ProductContract {
    static let repository = "smllthx/geneiai"
    static let version = "3.0.3"
    static let publicURL = URL(string: "https://geneiai.vercel.app")!
    static let publicHost = "geneiai.vercel.app"
}
