import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDeepStrictEqual } from 'node:util';

export function validateProduct(p, backend) {
  if (p?.schemaVersion !== 1 || p.name !== 'GENEAI' || p.repository !== 'smllthx/geneiai') throw new Error('Invalid product identity');
  if (p.publicOrigin !== 'https://geneiai.vercel.app') throw new Error('Unexpected canonical origin');
  if (p.backendProjectRef !== 'camdtylwddleifaegzaf' || backend.projectRef !== p.backendProjectRef) throw new Error('Unexpected backend project');
  if (backend.supabaseUrl !== `https://${p.backendProjectRef}.supabase.co`) throw new Error('Backend URL mismatch');
  if (!/^sb_publishable_[A-Za-z0-9_-]+$/.test(backend.publishableKey ?? '')) throw new Error('Public key required; secret keys are refused');
  if (!/^\d+\.\d+\.\d+$/.test(p.version ?? '') || !Number.isSafeInteger(p.build) || p.build < 1) throw new Error('Invalid version/build');
  if (p.appleBundleIdentifier !== 'com.genaia.app' || p.legacyTauriBundleIdentifier !== 'com.geneai.geneai') throw new Error('Native identity must be preserved');
  if (!['integration', 'stable'].includes(p.channel) || typeof p.nativeDistributionReady !== 'boolean') throw new Error('Invalid release state');
  if (p.apiContractVersion !== 1 || !/^\d{4}-\d{2}-\d{2}$/.test(p.publishedAt ?? '')) throw new Error('Invalid release contract');
  if (!Array.isArray(p.changes) || !p.changes.length || p.changes.length > 50 || p.changes.some(x => typeof x !== 'string' || !x.trim())) throw new Error('Invalid changelog');
  return p;
}

export function synchronize(root, { write = false } = {}) {
  const text = path => readFileSync(resolve(root, path), 'utf8');
  const json = path => JSON.parse(text(path));
  const p = validateProduct(json('config/geneai-product.json'), json('config/geneai-backend.json'));
  const outputs = new Map();
  const putJSON = (path, value) => outputs.set(path, JSON.stringify(value, null, 2) + '\n');
  const pkg = json('package.json');
  pkg.name = 'geneai'; pkg.version = p.version;
  putJSON('package.json', pkg);
  const lock = json('package-lock.json');
  lock.name = pkg.name; lock.version = p.version;
  if (lock.packages?.['']) { lock.packages[''].name = pkg.name; lock.packages[''].version = p.version; }
  putJSON('package-lock.json', lock);
  putJSON('public/release.json', { version: p.version, publishedAt: p.publishedAt, channel: p.channel, changes: p.changes, nativeDistributionReady: p.nativeDistributionReady });
  putJSON('public/geneai-runtime.json', { schemaVersion: 1, name: p.name, repository: p.repository, publicOrigin: p.publicOrigin, backendProjectRef: p.backendProjectRef, version: p.version, apiContractVersion: p.apiContractVersion, channel: p.channel, nativeDistributionReady: p.nativeDistributionReady });
  const deployment = json('vercel.json');
  deployment.env.GENEAI_PUBLIC_URL = p.publicOrigin;
  putJSON('vercel.json', deployment);
  const apple = 'apple/GENEAI/';
  let yml = text(apple + 'project.yml');
  yml = yml.replace(/CFBundleShortVersionString: "[^"]+"/, `CFBundleShortVersionString: "${p.version}"`).replace(/CFBundleVersion: "[^"]+"/, `CFBundleVersion: "${p.build}"`);
  if (!yml.includes(`PRODUCT_BUNDLE_IDENTIFIER: ${p.appleBundleIdentifier}`)) throw new Error('Apple identity mismatch');
  outputs.set(apple + 'project.yml', yml);
  let plist = text(apple + 'GENAIAApple/Info.plist');
  plist = plist.replace(/(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]+/, `$1${p.version}`).replace(/(<key>CFBundleVersion<\/key>\s*<string>)[^<]+/, `$1${p.build}`);
  outputs.set(apple + 'GENAIAApple/Info.plist', plist);
  outputs.set(apple + 'GENAIAApple/Support/ProductContract.swift', [
    '// Generated by scripts/sync-product.mjs. Do not edit.', 'import Foundation', '', 'enum ProductContract {',
    `    static let repository = ${JSON.stringify(p.repository)}`,
    `    static let version = ${JSON.stringify(p.version)}`,
    `    static let publicURL = URL(string: ${JSON.stringify(p.publicOrigin)})!`,
    `    static let publicHost = ${JSON.stringify(new URL(p.publicOrigin).hostname)}`, '}', ''
  ].join('\n'));
  const drift = [];
  for (const [path, expected] of outputs) {
    let actual; try { actual = text(path); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    let aligned = actual === expected;
    if (!aligned && actual !== undefined && path.endsWith('.json')) {
      try { aligned = isDeepStrictEqual(JSON.parse(actual), JSON.parse(expected)); } catch { aligned = false; }
    }
    if (!aligned) { drift.push(path); if (write) writeFileSync(resolve(root, path), expected); }
  }
  return drift;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const flags = process.argv.slice(2);
    if (flags.length !== 1 || !['--check', '--write'].includes(flags[0])) throw new Error('Usage: node scripts/sync-product.mjs --check|--write');
    const write = flags[0] === '--write';
    const drift = synchronize(fileURLToPath(new URL('../', import.meta.url)), { write });
    if (drift.length && !write) { console.error('Product configuration drift: ' + drift.join(', ')); process.exitCode = 1; }
    else console.log(write ? `Synchronized ${drift.length} product files.` : 'Product identity, backend, versions and native sources are aligned.');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
