// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { recordAiUsage } from '../../lib/aiUsage';
import { friendlyAiErrorMessage } from '../../lib/aiErrors';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
const inFlightInvokes = new Map<string, Promise<any>>();

const invokeKey = (functionName: string, options?: any) => {
  try {
    return `${functionName}:${JSON.stringify(options?.body ?? {})}`;
  } catch {
    return `${functionName}:uncached`;
  }
};

supabase.functions.invoke = (async (functionName: string, options?: any) => {
  const key = invokeKey(functionName, options);
  if (key !== `${functionName}:uncached` && inFlightInvokes.has(key)) {
    return await inFlightInvokes.get(key);
  }

  const pending = originalInvoke(functionName as any, options);
  if (key !== `${functionName}:uncached`) {
    inFlightInvokes.set(key, pending);
    pending.finally(() => window.setTimeout(() => inFlightInvokes.delete(key), 2500));
  }

  const result = await pending;
  try {
    recordAiUsage(functionName, options?.body, !result.error);
  } catch {}

  if (!result.error) {
    const dataError = (result.data as any)?.error;
    if (dataError) {
      (result.data as any).details = (result.data as any).details ?? dataError;
      (result.data as any).error = friendlyAiErrorMessage(dataError, functionName);
    }
    return result;
  }

  let detail = "";
  const context = (result.error as any).context;
  try {
    if (context?.clone) {
      const raw = await context.clone().text();
      if (raw) {
        try {
          const parsed = JSON.parse(raw);
          detail = parsed.error || parsed.message || raw;
        } catch {
          detail = raw;
        }
      }
    }
  } catch {
    detail = "";
  }

  const rawMessage = detail || result.error.message || "Error de IA";
  const friendly = friendlyAiErrorMessage(rawMessage, functionName);

  (result.error as any).message = friendly;
  (result.error as any).details = rawMessage;

  try {
    window.dispatchEvent(new CustomEvent("genaia:ia-error", {
      detail: { functionName, message: friendly, raw: rawMessage },
    }));
  } catch {}

  return result;
}) as typeof supabase.functions.invoke;
